import { StatItem, QuickActionItem, ActivityRecord, User } from '../types';

export const mockUser: User = {
  id: 'usr_9824',
  name: 'Alex Rivera',
  email: 'admin@wmsapp.com',
  role: 'Operations Director',
  facility: 'West Coast Hub #4',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
};

export const mockStats: StatItem[] = [
  {
    id: 'stat_1',
    title: 'Inbound Pallets',
    value: '1,428',
    change: '+14.2%',
    isPositive: true,
    iconName: 'download-outline',
    iconColor: '#4F46E5',
    bgColor: '#EEF2FF',
  },
  {
    id: 'stat_2',
    title: 'Outbound Dispatched',
    value: '984',
    change: '+8.5%',
    isPositive: true,
    iconName: 'paper-plane-outline',
    iconColor: '#0EA5E9',
    bgColor: '#E0F2FE',
  },
  {
    id: 'stat_3',
    title: 'Pick Accuracy',
    value: '99.8%',
    change: '+0.3%',
    isPositive: true,
    iconName: 'checkmark-done-circle-outline',
    iconColor: '#10B981',
    bgColor: '#D1FAE5',
  },
  {
    id: 'stat_4',
    title: 'Low Stock Alerts',
    value: '12',
    change: '-4 cases',
    isPositive: false,
    iconName: 'alert-circle-outline',
    iconColor: '#EF4444',
    bgColor: '#FEF2F2',
  },
];

export const mockQuickActions: QuickActionItem[] = [
  {
    id: 'qa_scan',
    title: 'Barcode Scan',
    subtitle: 'Fast SKU lookup',
    iconName: 'barcode-outline',
    badge: 'Live',
    color: '#4F46E5',
    bgLight: '#EEF2FF',
  },
  {
    id: 'qa_inbound',
    title: 'Receive Stock',
    subtitle: 'Gate 3 Inbound',
    iconName: 'cube-outline',
    badge: '3 Docs',
    color: '#0EA5E9',
    bgLight: '#E0F2FE',
  },
  {
    id: 'qa_pick',
    title: 'Order Picking',
    subtitle: 'Zone B & C active',
    iconName: 'cart-outline',
    color: '#10B981',
    bgLight: '#D1FAE5',
  },
  {
    id: 'qa_audit',
    title: 'Cycle Count',
    subtitle: 'Daily inventory audit',
    iconName: 'clipboard-outline',
    color: '#F59E0B',
    bgLight: '#FFFBEB',
  },
];

export const mockActivities: ActivityRecord[] = [
  {
    id: 'act_101',
    code: 'SHP-88219',
    title: 'High-Priority Electronics Docking',
    type: 'Inbound Freight',
    location: 'Dock A-12',
    itemsCount: 420,
    timestamp: '10 mins ago',
    status: 'PROCESSING',
    operator: 'Marcus Vance',
  },
  {
    id: 'act_102',
    code: 'ORD-77402',
    title: 'Express Retail Batch Outbound',
    type: 'Dispatch',
    location: 'Bay 4',
    itemsCount: 156,
    timestamp: '25 mins ago',
    status: 'IN_TRANSIT',
    operator: 'Elena Rostova',
  },
  {
    id: 'act_103',
    code: 'AUD-33901',
    title: 'Cold Storage Section Verification',
    type: 'Cycle Count',
    location: 'Freezer Zone 2',
    itemsCount: 88,
    timestamp: '1 hour ago',
    status: 'COMPLETED',
    operator: 'Sarah Jenkins',
  },
  {
    id: 'act_104',
    code: 'ALT-11048',
    title: 'SKU #9021 Temperature Threshold Alert',
    type: 'System Alert',
    location: 'Aisle 14B',
    itemsCount: 12,
    timestamp: '2 hours ago',
    status: 'ALERT',
    operator: 'Automated Sensor',
  },
];
