import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { SafeStorage } from '../utils/storage';

export type Language = 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  isHindi: boolean;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (keyOrText: string, fallback?: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Home / Dashboard
    'Good Morning': 'Good Morning',
    'Good Afternoon': 'Good Afternoon',
    'Good Evening': 'Good Evening',
    'Operations Lead': 'Operations Lead',
    'WAREHOUSE MODULES': 'WAREHOUSE MODULES',
    'MODULES': 'MODULES',
    'Packing': 'Packing',
    'Put Away': 'Put Away',
    'Carton registration, barcode SKU verification, container freight & pallet assignment': 'Carton registration, barcode SKU verification, container freight & pallet assignment',
    'Standard SKU bin putaway, bulk pallet routing, bin capacity tracking & aisle sorting': 'Standard SKU bin putaway, bulk pallet routing, bin capacity tracking & aisle sorting',
    'Open Packing Modules': 'Open Packing Modules',
    'Open Put Away Modules': 'Open Put Away Modules',

    // WMS Packing Screens
    'WMS PACKING MODULE': 'WMS PACKING MODULE',
    'WMS PACKING — SCANNING': 'WMS PACKING — SCANNING',
    'INBOUND PUTAWAY MODULE': 'INBOUND PUTAWAY MODULE',
    'INBOUND PUTAWAY SCANNING': 'INBOUND PUTAWAY SCANNING',
    'CONTAINER LOADING MODULE': 'CONTAINER LOADING MODULE',
    'Document Registration': 'Document Registration',
    'Assign picking lists & departments for packing verification': 'Assign picking lists & departments for packing verification',
    'Document Number': 'Document Number',
    'Select Document Number...': 'Select Document Number...',
    'Department Assignment': 'Department Assignment',
    'Select Department(s)...': 'Select Department(s)...',
    'Department(s) selected': 'Department(s) selected',
    'Register Document': 'Register Document',
    'Search document or department...': 'Search document or department...',
    'No registered documents found for scanning.': 'No registered documents found for scanning.',
    'Start Batch Scanning': 'Start Batch Scanning',
    'Container Registration': 'Container Registration',
    'Register container documents for freight & pallet loading': 'Register container documents for freight & pallet loading',
    'Container Document': 'Container Document',
    'Select Container Document...': 'Select Container Document...',
    'Department / Freight Zone': 'Department / Freight Zone',
    'Search container document or freight bay...': 'Search container document or freight bay...',
    'No registered containers found for loading.': 'No registered containers found for loading.',
    'Start Container Loading': 'Start Container Loading',
    'Packer Registration': 'Packer Registration',
    'Select one document and register one or more departments.': 'Select one document and register one or more departments.',
    'DOCUMENT NUMBER': 'DOCUMENT NUMBER',
    'Select document number': 'Select document number',
    'ORGANIZATION': 'ORGANIZATION',
    'DEPARTMENTS (MULTI)': 'DEPARTMENTS (MULTI)',
    'Select departments': 'Select departments',
    'Register Packer': 'Register Packer',
    'Registered Documents': 'Registered Documents',
    'Documents registered to your ID': 'Documents registered to your ID',
    'No registered documents': 'No registered documents',
    'Select and register a document above to begin': 'Select and register a document above to begin',
    'REGISTERED': 'REGISTERED',
    'Click to Scan': 'Click to Scan',
    'Select a registered document and departments below, then start scanning.': 'Select a registered document and departments below, then start scanning.',
    'Search registered documents...': 'Search registered documents...',
    'DOC NO': 'DOC NO',
    'SELECTED DOCUMENT': 'SELECTED DOCUMENT',
    'Click to Start Scanning': 'Click to Start Scanning',
    'Standard Carton Packing': 'Standard Carton Packing',
    'Carton Items Manifest': 'Carton Items Manifest',
    'BOX': 'BOX',
    'PKD': 'PKD',
    'No scanned items in cart': 'No scanned items in cart',
    'Scan barcode SKU using laser reader above': 'Scan barcode SKU using laser reader above',
    'Packed Items Total': 'Packed Items Total',
    'Complete Carton Packing': 'Complete Carton Packing',
    'Submitting Package...': 'Submitting Package...',
    'No Document': 'No Document',
    'scanned': 'scanned',
    'qty packed': 'qty packed',
    'Prev': 'Prev',
    'Next': 'Next',
    'CURRENT BOX': 'CURRENT BOX',
    'Box': 'Box',
    'Scanned Items': 'Scanned Items',
    'ALL BOXES': 'ALL BOXES',
    'Latest 5 of': 'Latest 5 of',
    'items': 'items',
    'Reload': 'Reload',
    'Loading scanning data...': 'Loading scanning data...',
    'No items scanned yet': 'No items scanned yet',
    'Scan a barcode above or trigger hardware laser': 'Scan a barcode above or trigger hardware laser',
    'ITEM SKU': 'ITEM SKU',
    'Submit Packing List': 'Submit Packing List',
    'lines': 'lines',
    'Ready': 'Ready',

    // Navigation & Headers
    'WMS Packing': 'WMS Packing',
    'Putaway Scanning': 'Putaway Scanning',
    'Container Packing': 'Container Packing',
    'Inventory': 'Inventory',
    'Operations': 'Operations',
    'Dashboard': 'Dashboard',
    'Settings': 'Settings',
    'Terminal Settings': 'Terminal Settings',
    'Sign Out': 'Sign Out',
    'Language': 'Language',
    'English': 'English',
    'Hindi': 'Hindi',
    'Register': 'Register',
    'Scan': 'Scan',
    'Change': 'Change',
    'Back': 'Back',
    'Submit': 'Submit',
    'Save': 'Save',
    'Cancel': 'Cancel',
    'Confirm': 'Confirm',
    'Close': 'Close',
    'Reset': 'Reset',
    'Clear': 'Clear',
    'Refresh': 'Refresh',
    'Search': 'Search',
    'Filter': 'Filter',
    'Done': 'Done',
    'Complete': 'Complete',

    // Screen Headers & Labels
    'Floor Operations': 'Floor Operations',
    'Packing, Logistics & Execution': 'Packing, Logistics & Execution',
    'PACKING MODULES': 'PACKING MODULES',
    'LOGISTICS & WAREHOUSE CONTROL': 'LOGISTICS & WAREHOUSE CONTROL',
    'Putaway Setup': 'Putaway Setup',
    'Inbound GRN & Bin Allocation': 'Inbound GRN & Bin Allocation',
    'Putaway Allocation Form': 'Putaway Allocation Form',
    'GRN DOCUMENT NUMBER': 'GRN DOCUMENT NUMBER',
    'DESTINATION BIN LOCATION': 'DESTINATION BIN LOCATION',
    'Start Putaway': 'Start Putaway',
    'Inventory & Stock': 'Inventory & Stock',
    'Warehouse SKU tracking': 'Warehouse SKU tracking',
    'Add Stock': 'Add Stock',
    'Search by SKU, item name, aisle...': 'Search by SKU, item name, aisle...',
    'Filter by Zone': 'Filter by Zone',
    'SHOWING': 'SHOWING',
    'SKUs': 'SKUs',
    'In Stock': 'In Stock',
    'Low Stock': 'Low Stock',
    'Units': 'Units',
    'WORKFLOWS': 'WORKFLOWS',
    'LIVE': 'LIVE',
    'API SYNC': 'API SYNC',
    'FREIGHT': 'FREIGHT',
    'LOGISTICS': 'LOGISTICS',
    'ACTIVE': 'ACTIVE',
    'Registration': 'Registration',
    'Scanning': 'Scanning',
    'Verify Items': 'Verify Items',
    'Pallet Loading': 'Pallet Loading',
    'Setup & Bin': 'Setup & Bin',
    'Bin Allocation': 'Bin Allocation',
    'Multi-GRN Select': 'Multi-GRN Select',
    'Single-Select': 'Single-Select',
    'BIN SET': 'BIN SET',
    'BILL NO': 'BILL NO',
    'BILL / VOUCH DATE': 'BILL / VOUCH DATE',
    'ASSIGNED DEPARTMENTS': 'ASSIGNED DEPARTMENTS',
    'DEPARTMENT': 'DEPARTMENT',
    'Dock & Gate Inbound': 'Dock & Gate Inbound',
    'Receive freight shipments & bills': 'Receive freight shipments & bills',
    'Outbound Dispatch': 'Outbound Dispatch',
    'Load assignment & bill of lading': 'Load assignment & bill of lading',
    'Cycle Counting': 'Cycle Counting',
    'Daily inventory discrepancy audit': 'Daily inventory discrepancy audit',
    'Forklift & AGV Control': 'Forklift & AGV Control',
    'Assign robotic pallet movers': 'Assign robotic pallet movers',
    'Packing Modules': 'Packing Modules',
    'PACKING HUB': 'PACKING HUB',
    'Select workflow module to begin registration or SKU scanning': 'Select workflow module to begin registration or SKU scanning',
    'Standard carton packing, document registration, department filter, and item verification': 'Standard carton packing, document registration, department filter, and item verification',
    'Container seal registration, pallet tier stacking, master carton assignment, and load manifest': 'Container seal registration, pallet tier stacking, master carton assignment, and load manifest',

    // Scanner & Cards
    'Hardware Scanner': 'Hardware Scanner',
    'TAP TO FOCUS': 'TAP TO FOCUS',
    'SCANNER FOCUSED': 'SCANNER FOCUSED',
    'Ready for laser barcode scan': 'Ready for laser barcode scan',
    'Tap to focus scanner': 'Tap to focus scanner',
    '● Scanner Active — Ready to scan SKU...': '● Scanner Active — Ready to scan SKU...',
    'Processing barcode scan...': 'Processing barcode scan...',

    // Cart & Stats
    'Bin Cart Allocation': 'Bin Cart Allocation',
    'TOTAL': 'TOTAL',
    'SCANNED': 'SCANNED',
    'PACKED': 'PACKED',
    'PENDING': 'PENDING',
    'PENDING ITEMS': 'PENDING ITEMS',
    'REVISED': 'REVISED',
    'CANCELLED': 'CANCELLED',
    'BINNED': 'BINNED',
    'VOID': 'VOID',
    'ORD': 'ORD',
    'PUT': 'PUT',
    'DIF': 'DIF',
    'STAT': 'STAT',

    // Container Packing Module
    'CONTAINER PACKING MODULE': 'CONTAINER PACKING MODULE',
    'Container Freight Registration': 'Container Freight Registration',
    'Assign container manifest and pallet tier bays': 'Assign container manifest and pallet tier bays',
    'CONTAINER / DOCUMENT NUMBER': 'CONTAINER / DOCUMENT NUMBER',
    'Select container number': 'Select container number',
    'BAYS / DEPARTMENTS': 'BAYS / DEPARTMENTS',
    'Select freight bays': 'Select freight bays',
    'Register Container': 'Register Container',
    'Container Loading': 'Container Loading',
    'Select container manifest below to start loading pallets.': 'Select container manifest below to start loading pallets.',
    'Search containers...': 'Search containers...',
    'CONTAINER NO': 'CONTAINER NO',
    'BAY': 'BAY',
    'No registered containers': 'No registered containers',
    'Register a container in the Register tab': 'Register a container in the Register tab',
    'Start Pallet Loading': 'Start Pallet Loading',
    'Select Container Document': 'Select Container Document',

    'Container Mode': 'Container Mode',
    'CONTAINER PACKING — LOADING': 'CONTAINER PACKING — LOADING',
    'No Container': 'No Container',
    'items loaded': 'items loaded',
    'PALLET / TIER': 'PALLET / TIER',
    'Container Manifest': 'Container Manifest',
    'Loading manifest data...': 'Loading manifest data...',
    'No items scanned to container': 'No items scanned to container',
    'Scan carton / SKU barcode to load onto pallet': 'Scan carton / SKU barcode to load onto pallet',
    'TIER': 'TIER',
    'DO': 'DO',
    'PCK': 'PCK',
    'CONTAINER STATISTICS': 'CONTAINER STATISTICS',
    'Container Loading Report': 'Container Loading Report',
    'LOADED': 'LOADED',
    'Close Report': 'Close Report',
    'Doc:': 'Doc:',
    'loaded': 'loaded',
    'Tier': 'Tier',
    'Scan Container': 'Scan Container',
    'ALL PALLETS': 'ALL PALLETS',
    'qty': 'qty',
    'Seal assignment & pallet freight verification': 'Seal assignment & pallet freight verification',
    '2 Screens': '2 Screens',
    'Document & Dept': 'Document & Dept',
    'Carton registration & SKU package scanning': 'Carton registration & SKU package scanning',
    'Seal': 'Seal',
    'Pallet': 'Pallet',
    'Carton': 'Carton',
    'Laser': 'Laser',
    'MAIN NAVIGATION': 'MAIN NAVIGATION',
    'LOGISTICS & WAREHOUSE': 'LOGISTICS & WAREHOUSE',
    'Container Freight': 'Container Freight',
    'Pallet Tier Stacking': 'Pallet Tier Stacking',
    'Cold Storage Bay': 'Cold Storage Bay',
    'Container': 'Container',
    'This action cannot be undone': 'This action cannot be undone',
    'REMARKS *': 'REMARKS *',
    'PACKED QUANTITY': 'PACKED QUANTITY',
    'Edit Packed Qty': 'Edit Packed Qty',
    'Will be marked REVISED': 'Will be marked REVISED',
    'Update Qty': 'Update Qty',
    'Balance Qty': 'Balance Qty',
    'DO FULLY PACKED (+EXTRA)': 'DO FULLY PACKED (+EXTRA)',
    'REMAINING': 'REMAINING',
    'ADD BALANCE QUANTITY': 'ADD BALANCE QUANTITY',
    'ADD EXTRA PACKED QTY': 'ADD EXTRA PACKED QTY',
    'Add Duplicate Move': 'Add Duplicate Move',
    'Add as New Row': 'Add as New Row',

    // Sheets & Data Sync Modal
    'Select Document': 'Select Document',
    'One document at a time': 'One document at a time',
    'available': 'available',
    'Search document number or client...': 'Search document number or client...',
    'No documents found': 'No documents found',
    'Try searching with another document number': 'Try searching with another document number',
    'department(s) available': 'department(s) available',
    'Select Departments': 'Select Departments',
    'Search departments...': 'Search departments...',
    'Deselect All Departments': 'Deselect All Departments',
    'Select All Departments': 'Select All Departments',
    'Deselect All Documents': 'Deselect All Documents',
    'Select All Documents': 'Select All Documents',
    'No departments available': 'No departments available',
    'Confirm Selection': 'Confirm Selection',
    'Syncing Picklist Data': 'Syncing Picklist Data',
    'Picklist Sync Complete': 'Picklist Sync Complete',
    'Cached locally': 'Cached locally',
    'Sync progress': 'Sync progress',
    'items indexed for 0ms scan': 'items indexed for 0ms scan',
    'Preparing picklist data...': 'Preparing picklist data...',

    // Modals & Forms
    'Duplicate Item': 'Duplicate Item',
    'This item was already scanned': 'This item was already scanned',
    'Edit Quantity': 'Edit Quantity',
    'Cancel Item': 'Cancel Item',
    'Enter cancellation remarks...': 'Enter cancellation remarks...',
    'SCAN STATISTICS': 'SCAN STATISTICS',
    'Scan Statistics Report': 'Scan Statistics Report',
    'PACKING STATISTICS & PROGRESS': 'PACKING STATISTICS & PROGRESS',

    // Putaway Scanning Module
    'Select GRN Documents': 'Select GRN Documents',
    'MULTI-SELECT': 'MULTI-SELECT',
    'Selected': 'Selected',
    'Choose 1 of': 'Choose 1 of',
    'GRNs': 'GRNs',
    'GRNs selected': 'GRNs selected',
    'Search GRN number, supplier, or zone...': 'Search GRN number, supplier, or zone...',
    'Select All GRNs': 'Select All GRNs',
    'Deselect All GRNs': 'Deselect All GRNs',
    'No GRN documents match': 'No GRN documents match',
    'ITEM': 'ITEM',
    'ITEMS': 'ITEMS',
    'Bill': 'Bill',
    'Select inbound GRN document and assign destination Bin location for hardware laser scanning.': 'Select inbound GRN document and assign destination Bin location for hardware laser scanning.',
    'Loading GRN assignments...': 'Loading GRN assignments...',
    'Select GRN document': 'Select GRN document',
    'Please select a GRN document to start putaway.': 'Please select a GRN document to start putaway.',
    'Target Bin Required': 'Target Bin Required',
    'Please enter destination Bin location.': 'Please enter destination Bin location.',
    'Validating Bin Location...': 'Validating Bin Location...',
    'Invalid Bin Location': 'Invalid Bin Location',
    'Connecting to WMS server...': 'Connecting to WMS server...',
    'Syncing Inbound GRN Data': 'Syncing Inbound GRN Data',
    'GRN Items Sync Complete': 'GRN Items Sync Complete',
    'Preparing Putaway...': 'Preparing Putaway...',
    'Setup Error': 'Setup Error',
    'Unable to start putaway. Please check network and try again.': 'Unable to start putaway. Please check network and try again.',
    'Enter destination Bin (e.g. G1, BIN-A1-01)...': 'Enter destination Bin (e.g. G1, BIN-A1-01)...',
    'Inbound Supplier': 'Inbound Supplier',
    'Show less': 'Show less',
    'more': 'more',
    'Putaway Manifest': 'Putaway Manifest',
    'Units Binned': 'Units Binned',
    'No items scanned to bin': 'No items scanned to bin',
    'Trigger hardware scanner to allocate SKUs into': 'Trigger hardware scanner to allocate SKUs into',
    'BIN': 'BIN',
    'SKU': 'SKU',
    'Showing latest 5 of': 'Showing latest 5 of',
    'putaway items · All items are saved & counted': 'putaway items · All items are saved & counted',
    'PUTAWAY SUMMARY': 'PUTAWAY SUMMARY',
    'TOTAL LINES': 'TOTAL LINES',
    'UNITS BINNED': 'UNITS BINNED',
    'GRN LINKED': 'GRN LINKED',
    'Submit Putaway': 'Submit Putaway',
    'Confirm & Submit': 'Confirm & Submit',
    'Putaway Completed': 'Putaway Completed',
    'Successfully allocated': 'Successfully allocated',
    'Item Not Found in GRN': 'Item Not Found in GRN',
    'Department Warning': 'Department Warning',
    'No Items': 'No Items',
    'Please scan at least one item into the target bin.': 'Please scan at least one item into the target bin.',
    'Invalid Quantity': 'Invalid Quantity',
    'Please enter a valid quantity.': 'Please enter a valid quantity.',
    'Please enter a valid number.': 'Please enter a valid number.',
    'DO Qty': 'DO Qty',
    'Packed': 'Packed',

    // Auth & Login
    'TERMINAL ONLINE': 'TERMINAL ONLINE',
    'Sign In': 'Sign In',
    'Enter operator credentials for this terminal': 'Enter operator credentials for this terminal',
    'USER ID / EMAIL': 'USER ID / EMAIL',
    'PASSWORD': 'PASSWORD',
    'Enter terminal password': 'Enter terminal password',
    'Remember credentials on this terminal': 'Remember credentials on this terminal',
    'Sign In to Terminal': 'Sign In to Terminal',
    'Invalid User ID or Password. Please try again.': 'Invalid User ID or Password. Please try again.',
    'Please enter your Operator / Employee ID or Email': 'Please enter your Operator / Employee ID or Email',
    'Please enter your password': 'Please enter your password',
    'Authentication error. Please check your connection.': 'Authentication error. Please check your connection.',
    'FACILITY': 'FACILITY',
    'GATEWAY': 'GATEWAY',
    'MODE': 'MODE',
    'WH-01 MAIN': 'WH-01 MAIN',
    'LASER / SYNC': 'LASER / SYNC',
    'Are you sure you want to end your terminal session?': 'Are you sure you want to end your terminal session?',
    'Item Not Found': 'Item Not Found',
    'Scan Error': 'Scan Error',
    'Unable to process barcode.': 'Unable to process barcode.',
    'Please enter a valid quantity (minimum 1).': 'Please enter a valid quantity (minimum 1).',
    'No Scanned Items': 'No Scanned Items',
    'Unable to check pending items before submission.': 'Unable to check pending items before submission.',
    'Mark Pending 0': 'Mark Pending 0',
    'Mark Pending Items as 0': 'Mark Pending Items as 0',
    'Mark 0 & Add to Cart': 'Mark 0 & Add to Cart',
    'No Pending Items': 'No Pending Items',
    'Items Marked as 0': 'Items Marked as 0',
    'Cannot Submit - Pending Items Remaining': 'Cannot Submit - Pending Items Remaining',
    'All items in the picklist have already been scanned or marked as 0.': 'All items in the picklist have already been scanned or marked as 0.',
    'See More': 'See More',
    'See Less': 'See Less',
    'Showing all': 'Showing all',
  },
  hi: {
    // Home / Dashboard
    'Good Morning': 'शुभ प्रभात',
    'Good Afternoon': 'शुभ अपराह्न',
    'Good Evening': 'शुभ संध्या',
    'Operations Lead': 'ऑपरेशन्स लीड',
    'WAREHOUSE MODULES': 'वेयरहाउस मॉड्यूल्स',
    'MODULES': 'मॉड्यूल',
    'Packing': 'पैकिंग',
    'Put Away': 'पुटअवे',
    'Carton registration, barcode SKU verification, container freight & pallet assignment': 'कार्टन पंजीकरण, बारकोड SKU सत्यापन, कंटेनर फ्रेट और पैलेट आवंटन',
    'Standard SKU bin putaway, bulk pallet routing, bin capacity tracking & aisle sorting': 'मानक SKU बिन पुटअवे, बल्क पैलेट रूटिंग, बिन क्षमता ट्रैकिंग और ऐल छँटाई',
    'Open Packing Modules': 'पैकिंग मॉड्यूल्स खोलें',
    'Open Put Away Modules': 'पुटअवे मॉड्यूल्स खोलें',

    // WMS Packing Screens
    'WMS PACKING MODULE': 'WMS पैकिंग मॉड्यूल',
    'WMS PACKING — SCANNING': 'WMS पैकिंग — स्कैनिंग',
    'INBOUND PUTAWAY MODULE': 'इनबाउंड पुटअवे मॉड्यूल',
    'INBOUND PUTAWAY SCANNING': 'इनबाउंड पुटअवे स्कैनिंग',
    'CONTAINER LOADING MODULE': 'कंटेनर लोडिंग मॉड्यूल',
    'Document Registration': 'दस्तावेज़ पंजीकरण',
    'Assign picking lists & departments for packing verification': 'पैकिंग सत्यापन के लिए पिकिंग सूचियां और विभाग आवंटित करें',
    'Document Number': 'दस्तावेज़ संख्या',
    'Select Document Number...': 'दस्तावेज़ संख्या चुनें...',
    'Department Assignment': 'विभाग आवंटन',
    'Select Department(s)...': 'विभाग चुनें...',
    'Department(s) selected': 'विभाग चयनित',
    'Register Document': 'दस्तावेज़ पंजीकृत करें',
    'Search document or department...': 'दस्तावेज़ या विभाग खोजें...',
    'No registered documents found for scanning.': 'स्कैनिंग के लिए कोई पंजीकृत दस्तावेज़ नहीं मिले।',
    'Start Batch Scanning': 'बैच स्कैनिंग शुरू करें',
    'Container Registration': 'कंटेनर पंजीकरण',
    'Register container documents for freight & pallet loading': 'फ्रेट और पैलेट लोडिंग के लिए कंटेनर दस्तावेज़ पंजीकृत करें',
    'Container Document': 'कंटेनर दस्तावेज़',
    'Select Container Document...': 'कंटेनर दस्तावेज़ चुनें...',
    'Department / Freight Zone': 'विभाग / फ्रेट ज़ोन',
    'Search container document or freight bay...': 'कंटेनर दस्तावेज़ या फ्रेट बे खोजें...',
    'No registered containers found for loading.': 'लोडिंग के लिए कोई पंजीकृत कंटेनर नहीं मिले।',
    'Start Container Loading': 'कंटेनर लोडिंग शुरू करें',
    'Packer Registration': 'पैकर पंजीकरण',
    'Select one document and register one or more departments.': 'एक दस्तावेज़ चुनें और एक या अधिक विभागों को पंजीकृत करें।',
    'DOCUMENT NUMBER': 'दस्तावेज़ संख्या',
    'Select document number': 'दस्तावेज़ संख्या चुनें',
    'ORGANIZATION': 'संगठन',
    'DEPARTMENTS (MULTI)': 'विभाग (बहु-चयन)',
    'Select departments': 'विभाग चुनें',
    'Register Packer': 'पैकर पंजीकृत करें',
    'Registered Documents': 'पंजीकृत दस्तावेज़',
    'Documents registered to your ID': 'आपकी ID पर पंजीकृत दस्तावेज़',
    'No registered documents': 'कोई पंजीकृत दस्तावेज़ नहीं',
    'Select and register a document above to begin': 'शुरू करने के लिए ऊपर एक दस्तावेज़ चुनें और पंजीकृत करें',
    'REGISTERED': 'पंजीकृत',
    'Click to Scan': 'स्कैन करने के लिए क्लिक करें',
    'Select a registered document and departments below, then start scanning.': 'नीचे एक पंजीकृत दस्तावेज़ और विभाग चुनें, फिर स्कैनिंग शुरू करें।',
    'Search registered documents...': 'पंजीकृत दस्तावेज़ खोजें...',
    'DOC NO': 'दस्तावेज़ संख्या',
    'SELECTED DOCUMENT': 'चयनित दस्तावेज़',
    'Click to Start Scanning': 'स्कैनिंग शुरू करने के लिए क्लिक करें',
    'Standard Carton Packing': 'मानक कार्टन पैकिंग',
    'Carton Items Manifest': 'कार्टन सामग्री मैनिफेस्ट',
    'BOX': 'बॉक्स',
    'PKD': 'पैक्ड',
    'No scanned items in cart': 'कार्ट में कोई स्कैन किया गया आइटम नहीं',
    'Scan barcode SKU using laser reader above': 'ऊपर दिए गए लेजर रीडर से बारकोड SKU स्कैन करें',
    'Packed Items Total': 'कुल पैक्ड आइटम',
    'Complete Carton Packing': 'कार्टन पैकिंग पूर्ण करें',
    'Submitting Package...': 'पैकेज जमा हो रहा है...',
    'No Document': 'कोई दस्तावेज़ नहीं',
    'scanned': 'स्कैन किया गया',
    'qty packed': 'मात्रा पैक्ड',
    'Prev': 'पिछला',
    'Next': 'अगला',
    'CURRENT BOX': 'वर्तमान बॉक्स',
    'Box': 'बॉक्स',
    'Scanned Items': 'स्कैन किए गए आइटम',
    'ALL BOXES': 'सभी बॉक्स',
    'Latest 5 of': 'नवीनतम 5 में से',
    'items': 'आइटम',
    'Reload': 'रीलोड',
    'Loading scanning data...': 'स्कैनिंग डेटा लोड हो रहा है...',
    'No items scanned yet': 'अभी तक कोई आइटम स्कैन नहीं हुआ',
    'Scan a barcode above or trigger hardware laser': 'ऊपर बारकोड स्कैन करें या लेजर ट्रिगर करें',
    'ITEM SKU': 'आइटम SKU',
    'Submit Packing List': 'पैकिंग सूची जमा करें',
    'lines': 'लाइनें',
    'Ready': 'तैयार',

    // Navigation & Headers
    'WMS Packing': 'WMS पैकिंग',
    'Putaway Scanning': 'पुटअवे स्कैनिंग',
    'Container Packing': 'कंटेनर पैकिंग',
    'Inventory': 'इन्वेंटरी',
    'Operations': 'ऑपरेशन्स',
    'Dashboard': 'डैशबोर्ड',
    'Settings': 'सेटिंग्स',
    'Terminal Settings': 'टर्मिनल सेटिंग्स',
    'Sign Out': 'साइन आउट',
    'Language': 'भाषा',
    'English': 'English',
    'Hindi': 'हिंदी',
    'Register': 'पंजीकरण',
    'Scan': 'स्कैन',
    'Change': 'बदलें',
    'Back': 'वापस',
    'Submit': 'जमा करें',
    'Save': 'सहेजें',
    'Cancel': 'रद्द करें',
    'Confirm': 'पुष्टि करें',
    'Close': 'बंद करें',
    'Reset': 'रीसेट',
    'Clear': 'साफ़ करें',
    'Refresh': 'रिफ्रेश',
    'Search': 'खोजें',
    'Filter': 'फ़िल्टर',
    'Done': 'संपन्न',
    'Complete': 'पूर्ण',

    // Screen Headers & Labels
    'Floor Operations': 'फ़्लोर ऑपरेशन्स',
    'Packing, Logistics & Execution': 'पैकिंग, लॉजिस्टिक्स और निष्पादन',
    'PACKING MODULES': 'पैकिंग मॉड्यूल',
    'LOGISTICS & WAREHOUSE CONTROL': 'लॉजिस्टिक्स और वेयरहाउस नियंत्रण',
    'Putaway Setup': 'पुटअवे सेटअप',
    'Inbound GRN & Bin Allocation': 'इनबाउंड GRN और बिन आवंटन',
    'Putaway Allocation Form': 'पुटअवे आवंटन फॉर्म',
    'GRN DOCUMENT NUMBER': 'GRN दस्तावेज़ संख्या',
    'DESTINATION BIN LOCATION': 'गंतव्य बिन स्थान',
    'Start Putaway': 'पुटअवे शुरू करें',
    'Inventory & Stock': 'इन्वेंटरी और स्टॉक',
    'Warehouse SKU tracking': 'वेयरहाउस SKU ट्रैकिंग',
    'Add Stock': 'स्टॉक जोड़ें',
    'Search by SKU, item name, aisle...': 'SKU, नाम या स्थान से खोजें...',
    'Filter by Zone': 'ज़ोन अनुसार फ़िल्टर',
    'SHOWING': 'दिखा रहा है',
    'SKUs': 'SKUs',
    'In Stock': 'स्टॉक में उपलब्ध',
    'Low Stock': 'कम स्टॉक',
    'Units': 'इकाइयाँ',
    'WORKFLOWS': 'वर्कफ़्लो',
    'LIVE': 'लाइव',
    'API SYNC': 'API सिंक',
    'FREIGHT': 'फ्रेट',
    'LOGISTICS': 'लॉजिस्टिक्स',
    'ACTIVE': 'सक्रिय',
    'Registration': 'पंजीकरण',
    'Scanning': 'स्कैनिंग',
    'Verify Items': 'सामग्री जांचें',
    'Pallet Loading': 'पैलेट लोडिंग',
    'Setup & Bin': 'सेटअप और बिन',
    'Bin Allocation': 'बिन आवंटन',
    'Multi-GRN Select': 'मल्टी-GRN चुनें',
    'Single-Select': 'एक चुनें',
    'BIN SET': 'बिन सेट',
    'BILL NO': 'बिल संख्या',
    'BILL / VOUCH DATE': 'बिल / वाउचर तिथि',
    'ASSIGNED DEPARTMENTS': 'आवंटित विभाग',
    'DEPARTMENT': 'विभाग',
    'Dock & Gate Inbound': 'डॉक और गेट इनबाउंड',
    'Receive freight shipments & bills': 'माल लदान और बिल प्राप्त करें',
    'Outbound Dispatch': 'आउटबाउंड प्रेषण',
    'Load assignment & bill of lading': 'लोड आवंटन और लदान पत्र',
    'Cycle Counting': 'चक्र गणना',
    'Daily inventory discrepancy audit': 'दैनिक सूची विसंगति ऑडिट',
    'Forklift & AGV Control': 'फ़ॉर्कलिफ़्ट और AGV नियंत्रण',
    'Assign robotic pallet movers': 'रोबोटिक पैलेट मूवर्स आवंटित करें',
    'Packing Modules': 'पैकिंग मॉड्यूल्स',
    'PACKING HUB': 'पैकिंग हब',
    'Select workflow module to begin registration or SKU scanning': 'पंजीकरण या SKU स्कैनिंग शुरू करने के लिए कार्यप्रवाह मॉड्यूल चुनें',
    'Standard carton packing, document registration, department filter, and item verification': 'मानक कार्टन पैकिंग, दस्तावेज़ पंजीकरण, विभाग फ़िल्टर और आइटम सत्यापन',
    'Container seal registration, pallet tier stacking, master carton assignment, and load manifest': 'कंटेनर सील पंजीकरण, पैलेट स्टैकिंग, मास्टर कार्टन और लोड मैनिफेस्ट',

    // Container Packing Module
    'CONTAINER PACKING MODULE': 'कंटेनर पैकिंग मॉड्यूल',
    'Container Freight Registration': 'कंटेनर फ्रेट पंजीकरण',
    'Assign container manifest and pallet tier bays': 'कंटेनर मैनिफेस्ट और पैलेट टीयर स्थान आवंटित करें',
    'CONTAINER / DOCUMENT NUMBER': 'कंटेनर / दस्तावेज़ संख्या',
    'Select container number': 'कंटेनर संख्या चुनें',
    'BAYS / DEPARTMENTS': 'स्थान / विभाग',
    'Select freight bays': 'फ्रेट स्थान चुनें',
    'Register Container': 'कंटेनर पंजीकृत करें',
    'Container Loading': 'कंटेनर लोडिंग',
    'Select container manifest below to start loading pallets.': 'पैलेट लोड करना शुरू करने के लिए नीचे कंटेनर मैनिफेस्ट चुनें।',
    'Search containers...': 'कंटेनर खोजें...',
    'CONTAINER NO': 'कंटेनर संख्या',
    'BAY': 'स्थान',
    'No registered containers': 'कोई पंजीकृत कंटेनर नहीं',
    'Register a container in the Register tab': 'पंजीकरण टैब में एक कंटेनर पंजीकृत करें',
    'Start Pallet Loading': 'पैलेट लोडिंग शुरू करें',
    'Select Container Document': 'कंटेनर दस्तावेज़ चुनें',

    'Container Mode': 'कंटेनर मोड',
    'CONTAINER PACKING — LOADING': 'कंटेनर पैकिंग — लोडिंग',
    'No Container': 'कोई कंटेनर नहीं',
    'items loaded': 'आइटम लोड किए गए',
    'PALLET / TIER': 'पैलेट / टीयर',
    'Container Manifest': 'कंटेनर मैनिफेस्ट',
    'Loading manifest data...': 'मैनिफेस्ट डेटा लोड हो रहा है...',
    'No items scanned to container': 'कंटेनर में कोई आइटम स्कैन नहीं हुआ',
    'Scan carton / SKU barcode to load onto pallet': 'पैलेट पर लोड करने के लिए कार्टन / SKU बारकोड स्कैन करें',
    'TIER': 'टीयर',
    'DO': 'DO',
    'PCK': 'पैक्ड',
    'CONTAINER STATISTICS': 'कंटेनर आँकड़े',
    'Container Loading Report': 'कंटेनर लोडिंग रिपोर्ट',
    'LOADED': 'लोड किए गए',
    'Close Report': 'रिपोर्ट बंद करें',
    'Doc:': 'दस्तावेज़:',
    'loaded': 'लोड किए गए',
    'Tier': 'टीयर',
    'Scan Container': 'कंटेनर स्कैन',
    'ALL PALLETS': 'सभी पैलेट',
    'qty': 'मात्रा',
    'Seal assignment & pallet freight verification': 'सील आवंटन और पैलेट फ्रेट सत्यापन',
    '2 Screens': '2 स्क्रीन',
    'Document & Dept': 'दस्तावेज़ और विभाग',
    'Carton registration & SKU package scanning': 'कार्टन पंजीकरण और SKU पैकेज स्कैनिंग',
    'Seal': 'सील',
    'Pallet': 'पैलेट',
    'Carton': 'कार्टन',
    'Laser': 'लेजर',
    'MAIN NAVIGATION': 'मुख्य नेविगेशन',
    'LOGISTICS & WAREHOUSE': 'लॉजिस्टिक्स और वेयरहाउस',
    'Container Freight': 'कंटेनर फ्रेट',
    'Pallet Tier Stacking': 'पैलेट टीयर स्टैकिंग',
    'Cold Storage Bay': 'कोल्ड स्टोरेज बे',
    'Container': 'कंटेनर',
    'This action cannot be undone': 'यह क्रिया वापस नहीं की जा सकती',
    'REMARKS *': 'टिप्पणी *',
    'PACKED QUANTITY': 'पैक्ड मात्रा',
    'Edit Packed Qty': 'पैक्ड मात्रा बदलें',
    'Will be marked REVISED': 'संशोधित के रूप में चिह्नित किया जाएगा',
    'Update Qty': 'मात्रा अपडेट करें',
    'Balance Qty': 'शेष मात्रा',
    'DO FULLY PACKED (+EXTRA)': 'DO पूरी तरह पैक्ड (+अतिरिक्त)',
    'REMAINING': 'शेष',
    'ADD BALANCE QUANTITY': 'शेष मात्रा जोड़ें',
    'ADD EXTRA PACKED QTY': 'अतिरिक्त पैक्ड मात्रा जोड़ें',
    'Add Duplicate Move': 'डुप्लिकेट मूव जोड़ें',
    'Add as New Row': 'नई पंक्ति के रूप में जोड़ें',

    // Sheets & Data Sync Modal
    'Select Document': 'दस्तावेज़ चुनें',
    'One document at a time': 'एक समय में एक दस्तावेज़',
    'available': 'उपलब्ध',
    'Search document number or client...': 'दस्तावेज़ संख्या या ग्राहक खोजें...',
    'No documents found': 'कोई दस्तावेज़ नहीं मिला',
    'Try searching with another document number': 'किसी अन्य दस्तावेज़ संख्या से खोजने का प्रयास करें',
    'department(s) available': 'विभाग उपलब्ध',
    'Select Departments': 'विभाग चुनें',
    'Search departments...': 'विभाग खोजें...',
    'Deselect All Departments': 'सभी विभाग अचयनित करें',
    'Select All Departments': 'सभी विभाग चुनें',
    'Deselect All Documents': 'सभी दस्तावेज़ हटाएं',
    'Select All Documents': 'सभी दस्तावेज़ चुनें',
    'No departments available': 'कोई विभाग उपलब्ध नहीं',
    'Confirm Selection': 'चयन की पुष्टि करें',
    'Syncing Picklist Data': 'पिकलिस्ट डेटा सिंक हो रहा है',
    'Picklist Sync Complete': 'पिकलिस्ट सिंक पूर्ण हुआ',
    'Cached locally': 'स्थानीय रूप से सहेजा गया',
    'Sync progress': 'सिंक प्रगति',
    'items indexed for 0ms scan': 'आइटम 0ms स्कैन के लिए अनुक्रमित',
    'Preparing picklist data...': 'पिकलिस्ट डेटा तैयार किया जा रहा है...',

    // Scanner & Cards
    'Hardware Scanner': 'हार्डवेयर स्कैनर',
    'TAP TO FOCUS': 'फ़ोकस के लिए टैप करें',
    'SCANNER FOCUSED': 'स्कैनर सक्रिय है',
    'Ready for laser barcode scan': 'लेजर बारकोड स्कैन के लिए तैयार',
    'Tap to focus scanner': 'स्कैनर फ़ोकस करने के लिए टैप करें',
    '● Scanner Active — Ready to scan SKU...': '● स्कैनर सक्रिय — SKU स्कैन करें...',
    'Processing barcode scan...': 'बारकोड प्रोसेस हो रहा है...',

    // Cart & Stats
    'Bin Cart Allocation': 'बिन कार्ट आवंटन',
    'TOTAL': 'कुल',
    'SCANNED': 'स्कैन किया',
    'PACKED': 'पैक्ड',
    'PENDING': 'लंबित',
    'PENDING ITEMS': 'लंबित आइटम',
    'REVISED': 'संशोधित',
    'CANCELLED': 'रद्द किया',
    'BINNED': 'बिन में रखा',
    'VOID': 'रद्द',
    'ORD': 'ऑर्डर',
    'PUT': 'पुट',
    'DIF': 'अंतर',
    'STAT': 'स्थिति',

    // Modals & Forms
    'Duplicate Item': 'डुप्लिकेट आइटम',
    'This item was already scanned': 'यह आइटम पहले ही स्कैन किया जा चुका है',
    'Edit Quantity': 'मात्रा बदलें',
    'Cancel Item': 'आइटम रद्द करें',
    'Enter cancellation remarks...': 'रद्दीकरण की टिप्पणी लिखें...',
    'SCAN STATISTICS': 'स्कैन आँकड़े',
    'Scan Statistics Report': 'स्कैन सांख्यिकी रिपोर्ट',
    'PACKING STATISTICS & PROGRESS': 'पैकिंग आँकड़े और प्रगति',

    // Putaway Scanning Module
    'Select GRN Documents': 'GRN दस्तावेज़ चुनें',
    'MULTI-SELECT': 'मल्टी-चयन',
    'Selected': 'चयनित',
    'Choose 1 of': 'में से 1 चुनें',
    'GRNs': 'GRNs',
    'GRNs selected': 'GRN चयनित',
    'Search GRN number, supplier, or zone...': 'GRN संख्या, सप्लायर या ज़ोन खोजें...',
    'Select All GRNs': 'सभी GRN चुनें',
    'Deselect All GRNs': 'सभी GRN अचयनित करें',
    'No GRN documents match': 'कोई GRN दस्तावेज़ मेल नहीं खाता',
    'ITEM': 'आइटम',
    'ITEMS': 'आइटम',
    'Bill': 'बिल',
    'Select inbound GRN document and assign destination Bin location for hardware laser scanning.': 'इनबाउंड GRN दस्तावेज़ चुनें और हार्डवेयर लेजर स्कैनिंग के लिए गंतव्य बिन स्थान निर्दिष्ट करें।',
    'Loading GRN assignments...': 'GRN असाइनमेंट लोड हो रहे हैं...',
    'Select GRN document': 'GRN दस्तावेज़ चुनें',
    'Please select a GRN document to start putaway.': 'कृपया पुटअवे शुरू करने के लिए एक GRN दस्तावेज़ चुनें।',
    'Target Bin Required': 'गंतव्य बिन आवश्यक है',
    'Please enter destination Bin location.': 'कृपया गंतव्य बिन स्थान दर्ज करें।',
    'Validating Bin Location...': 'बिन स्थान का सत्यापन हो रहा है...',
    'Invalid Bin Location': 'अमान्य बिन स्थान',
    'Connecting to WMS server...': 'WMS सर्वर से कनेक्ट हो रहा है...',
    'Syncing Inbound GRN Data': 'इनबाउंड GRN डेटा सिंक हो रहा है',
    'GRN Items Sync Complete': 'GRN आइटम सिंक पूर्ण हुआ',
    'Preparing Putaway...': 'पुटअवे तैयार किया जा रहा है...',
    'Setup Error': 'सेटअप त्रुटि',
    'Unable to start putaway. Please check network and try again.': 'पुटअवे शुरू करने में असमर्थ। कृपया नेटवर्क की जाँच करें और पुनः प्रयास करें।',
    'Enter destination Bin (e.g. G1, BIN-A1-01)...': 'गंतव्य बिन दर्ज करें (उदा. G1, BIN-A1-01)...',
    'Inbound Supplier': 'इनबाउंड सप्लायर',
    'Show less': 'कम दिखाएं',
    'more': 'और',
    'Putaway Manifest': 'पुटअवे मैनिफेस्ट',
    'Units Binned': 'बिन में रखी इकाइयाँ',
    'No items scanned to bin': 'बिन में कोई आइटम स्कैन नहीं हुआ',
    'Trigger hardware scanner to allocate SKUs into': 'SKUs को आवंटित करने के लिए हार्डवेयर स्कैनर ट्रिगर करें',
    'BIN': 'बिन',
    'SKU': 'SKU',
    'Showing latest 5 of': 'कुल में से नवीनतम 5',
    'putaway items · All items are saved & counted': 'पुटअवे आइटम दिखाए जा रहे हैं · सभी आइटम सहेजे गए हैं',
    'PUTAWAY SUMMARY': 'पुटअवे सारांश',
    'TOTAL LINES': 'कुल लाइनें',
    'UNITS BINNED': 'बिन में रखी इकाइयाँ',
    'GRN LINKED': 'GRN लिंक हुआ',
    'Submit Putaway': 'पुटअवे जमा करें',
    'Confirm & Submit': 'पुष्टि करें और जमा करें',
    'Putaway Completed': 'पुटअवे पूर्ण हुआ',
    'Successfully allocated': 'सफलतापूर्वक आवंटित किया गया',
    'Item Not Found in GRN': 'GRN में आइटम नहीं मिला',
    'Department Warning': 'विभाग चेतावनी',
    'No Items': 'कोई आइटम नहीं',
    'Please scan at least one item into the target bin.': 'कृपया लक्ष्य बिन में कम से कम एक आइटम स्कैन करें।',
    'Invalid Quantity': 'अमान्य मात्रा',
    'Please enter a valid quantity.': 'कृपया एक मान्य मात्रा दर्ज करें।',
    'Please enter a valid number.': 'कृपया एक मान्य संख्या दर्ज करें।',
    'DO Qty': 'DO मात्रा',
    'Packed': 'पैक्ड',

    // Auth & Login
    'TERMINAL ONLINE': 'टर्मिनल ऑनलाइन',
    'Sign In': 'साइन इन',
    'Enter operator credentials for this terminal': 'इस टर्मिनल के लिए ऑपरेटर क्रेडेंशियल दर्ज करें',
    'USER ID / EMAIL': 'उपयोगकर्ता ID / ईमेल',
    'PASSWORD': 'पासवर्ड',
    'Enter terminal password': 'टर्मिनल पासवर्ड दर्ज करें',
    'Remember credentials on this terminal': 'इस टर्मिनल पर क्रेडेंशियल याद रखें',
    'Sign In to Terminal': 'टर्मिनल पर साइन इन करें',
    'Invalid User ID or Password. Please try again.': 'अमान्य उपयोगकर्ता ID या पासवर्ड। कृपया पुनः प्रयास करें।',
    'Please enter your Operator / Employee ID or Email': 'कृपया अपना ऑपरेटर / कर्मचारी ID या ईमेल दर्ज करें',
    'Please enter your password': 'कृपया अपना पासवर्ड दर्ज करें',
    'Authentication error. Please check your connection.': 'प्रमाणीकरण त्रुटि। कृपया अपना कनेक्शन जांचें।',
    'FACILITY': 'सुविधा',
    'GATEWAY': 'गेटवे',
    'MODE': 'मोड',
    'WH-01 MAIN': 'WH-01 मुख्य',
    'LASER / SYNC': 'लेजर / सिंक',
    'Are you sure you want to end your terminal session?': 'क्या आप वाकई अपना टर्मिनल सत्र समाप्त करना चाहते हैं?',
    'Item Not Found': 'आइटम नहीं मिला',
    'Scan Error': 'स्कैन त्रुटि',
    'Unable to process barcode.': 'बारकोड प्रोसेस करने में असमर्थ।',
    'Please enter a valid quantity (minimum 1).': 'कृपया एक मान्य मात्रा दर्ज करें (न्यूनतम 1)।',
    'No Scanned Items': 'कोई स्कैन किया गया आइटम नहीं',
    'Unable to check pending items before submission.': 'सबमिशन से पहले लंबित आइटम की जांच करने में असमर्थ।',
    'Mark Pending 0': 'पेंडिंग 0 मार्क करें',
    'Mark Pending Items as 0': 'पेंडिंग आइटम 0 मार्क करें',
    'Mark 0 & Add to Cart': '0 मार्क करें और कार्ट में जोड़ें',
    'No Pending Items': 'कोई पेंडिंग आइटम नहीं',
    'Items Marked as 0': 'आइटम 0 मार्क हो गए',
    'Cannot Submit - Pending Items Remaining': 'सबमिट नहीं किया जा सकता - पेंडिंग आइटम बाकी हैं',
    'All items in the picklist have already been scanned or marked as 0.': 'पिकलिस्ट के सभी आइटम पहले ही स्कैन किए जा चुके हैं या 0 के रूप में चिह्नित हैं।',
    'See More': 'और देखें',
    'See Less': 'कम देखें',
    'Showing all': 'सभी देखें',
  },
};

const LANGUAGE_STORAGE_KEY = 'wms_app_language';

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  isHindi: false,
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (keyOrText: string, fallback?: string) => fallback || keyOrText,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    loadSavedLanguage();
  }, []);

  const loadSavedLanguage = async () => {
    try {
      const saved = await SafeStorage.getItem(LANGUAGE_STORAGE_KEY);
      if (saved === 'hi' || saved === 'en') {
        setLanguageState(saved);
      }
    } catch (e) {
      console.log('Failed to load saved language:', e);
    }
  };

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    try {
      await SafeStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
    } catch (e) {
      console.log('Failed to save language preference:', e);
    }
  };

  const toggleLanguage = () => {
    const next: Language = language === 'en' ? 'hi' : 'en';
    setLanguage(next);
  };

  const t = (keyOrText: string, fallback?: string): string => {
    if (!keyOrText) return '';
    if (language === 'en') {
      return fallback || keyOrText;
    }

    const clean = keyOrText.trim();
    const dict = translations.hi;
    if (dict[clean]) return dict[clean];
    if (dict[clean.toLowerCase()]) return dict[clean.toLowerCase()];

    return fallback || keyOrText;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        isHindi: language === 'hi',
        setLanguage,
        toggleLanguage,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
